#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH --ntasks-per-node=1
#SBATCH -t 02:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=XXXXXXX

module load gromacs/2020.2-cpu

declare -a arrold=("ome2" "ome3" "ome4" "ome5" "ome6" "ome7" "ome8" "ome9" "ome10" "ome11") ## C36 parameters


 
for i in {0..9} ; do
 
 echo ${arrold[i]} | mpirun -np 1 gmx_mpi angle -f ../18-input.xtc  -type dihedral -ov "${arrold[i]}_metaD.xvg" -n index_diheds.ndx
done
 
 

 

